apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: wsgi-server-test
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: true
  artifacts:
    - image: mur6/internal-api-server-test
deploy:
  kustomize:
    paths:
      - k8s/
