apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: wsgi-server-test
build:
  tagPolicy:
    gitCommit: {}
  local:
    push: true
  artifacts:
    - image: docker.pkg.github.com/mur6/internal-api-server-test/simpleapi
deploy:
  kustomize:
    paths:
      - k8s/
