apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: prediction-app
spec:
  selector:
    matchLabels:
      app: prediction-app
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prediction-app
    spec:
      containers:
        - name: prediction-app
          image: mur6/internal-api-server-test
          env:
            - name: WORKERS
              value: "2"
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      imagePullSecrets:
        - name: regcred
